apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  volumes:
    - name: felgstorage
      persistentVolumeClaim:
        claimName: felgvol
  containers:
    - name: felg-container
      image: nvcr.io/nvidia/digits:19.12-tensorflow-py3
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
      volumeMounts:
        - mountPath: "/mnt/felvol"
          name: felgstorage
